{% set name = "yaqd-horiba" %}
{% set version = "2023.1.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 4c88c437aa6c4f1ebacaa3d9953f8031abb4d16c340b6a97bfdf1da03e947431

build:
  number: 0
  noarch: python
  entry_points:
    - yaqd-horiba-micro-hr = yaqd_horiba._microhr:MicroHR.main
    - yaqd-horiba-ihr320 = yaqd_horiba._horiba_ihr:HoribaIHR320.main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - pip
    - flit
    - pyusb
    - yaqd-core >=2020.06.3
  run:
    - python >=3.7
    - pyusb
    - yaqd-core >=2020.06.3

test:
  imports:
    - yaqd_horiba
  commands:
    - pip check
    - yaqd-horiba-micro-hr --help
    - yaqd-horiba-ihr320 --help
  requires:
    - pip

about:
  home: https://yaq.fyi
  summary: yaq daemons for Horiba Jobin Yvon hardware
  dev_url: https://gitlab.com/yaq/yaqd-horiba
  license: LGPL-3.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - untzag
    - ksunden
